// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/8/2026, 1:55:01 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/gaurav/Documents/car rental/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gaurav/Documents/car rental/website/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gaurav/Documents/car rental/website/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gaurav/Documents/car rental/website/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gaurav/Documents/car rental/website/plugins/**/*.{js,ts,mjs}","/home/gaurav/Documents/car rental/website/composables/**/*.{js,ts,mjs}","/home/gaurav/Documents/car rental/website/utils/**/*.{js,ts,mjs}","/home/gaurav/Documents/car rental/website/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gaurav/Documents/car rental/website/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gaurav/Documents/car rental/website/app.config.{js,ts,mjs}","/home/gaurav/Documents/car rental/website/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;